### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ilyesky** [udacity/andfun-kotlin-dessert-pusher#8]
https://github.com/udacity/andfun-kotlin-dessert-pusher/blob/2e0087dd93756d934dfff3730d40275d584d10aa/app/src/main/java/com/example/android/dessertpusher/MainActivity.kt#L183
required Bundle ,found Bundle?

**Comment by meening42** [comment]
Solved it by removing '?' after bundle. 
https://stackoverflow.com/questions/47049471/kotlin-oncreate-overrides-nothing/48112765
